# Generated by Django 5.0.6 on 2024-06-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='rent_start_date',
            field=models.DateTimeField(),
        ),
    ]
