# Generated by Django 5.0.6 on 2024-05-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IHA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(choices=[('AKINCI', 'Akinci'), ('DIHA', 'Diha'), ('MINI IHA', 'Mini IHA'), ('TB2', 'TB2'), ('TB3', 'TB2')], max_length=30)),
                ('weight', models.CharField(choices=[('IHA 0', 'IHA 0'), ('IHA 1', 'IHA 1'), ('IHA 2', 'IHA 2'), ('IHA 3', 'IHA 3')], max_length=10)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
