# Generated by Django 5.0.6 on 2024-05-22 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ihas', '0001_initial'),
        ('rents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='iha',
            name='rented_by',
            field=models.ManyToManyField(through='rents.Rent', to=settings.AUTH_USER_MODEL),
        ),
    ]
